version=1

[[annotations]]
path = [
    "Tanks/Assets/Scenes/**",
    "Tanks/Assets/Shaders/**",
    "Tanks/Assets/Scripts/**",
    "Tanks/Assets/Animations/**",
    "Tanks/Assets/Materials/**",
    "Tanks/Assets/Prefab/**",
    "Tanks/Packages/**",
    "README.md",
    ".gitignore",
    "REUSE.toml",
    "Tanks/.gitignore",
    "Tanks/steam_appid.txt",
    "Tanks/**/*.meta",
    "Tanks/ProjectSettings/**"
    ]
precedence = "override"
SPDX-FileCopyrightText = "2024 The Catanks Contributors"
SPDX-License-Identifier = "MPL-2.0"

[[annotations]]
path = [
    "Tanks/Assets/Models/**",
    "Tanks/Assets/Images/**",
    "AchievementsWithBorders/**",
    "Tanks/Assets/Audio/CustomSoundEffects/**",
    "Tanks/Assets/Audio/OfficialTracks/**"
    ]
precedence = "override"
SPDX-FileCopyrightText = "2024 The Catanks Contributors"
SPDX-License-Identifier = "CC-BY-SA-4.0"


[[annotations]]
path = ["Tanks/Assets/LeanTween/**"]
precedence = "override"
SPDX-FileCopyrightText = "2017 Russell Savage, Robert Penner"
SPDX-License-Identifier = "LicenseRef-MIT-LeanTween"

[[annotations]]
path = ["Tanks/Assets/Audio/OpenSourceSounds/CC0/**"]
precedence = "override"
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path="Tanks/Assets/Audio/OpenSourceSounds/Other/mechanical-gadget.mp3"
precedence = "override"
SPDX-FileCopyrightText = ["2024 The Catanks Contributors", "kiddpark"]
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = ["Audio modified by The Catank Contributors.\nOriginal File made by kiddpark, licensed under CC-BY-4.0:\nCash Register by kiddpark -- https://freesound.org/s/201159/ -- License: Attribution 4.0"]

[[annotations]]
path="Tanks/Assets/Audio/OpenSourceSounds/Other/bounce.wav"
precedence = "override"
SPDX-FileCopyrightText = ["NoiseCollector"]
SPDX-License-Identifier = "CC-BY-3.0"
SPDX-FileComment = ["Sound by NoiseCollector -- https://freesound.org/s/111361/ -- License: Attribution 3.0"]


