//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""TankControls"",
            ""id"": ""99ee5e7a-686f-4604-b5cf-0306c612658d"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""07e3dc7a-5cf7-4824-8683-7f96534b3951"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateGun"",
                    ""type"": ""Value"",
                    ""id"": ""a3343f72-e792-47b4-9610-b41a9a46fc76"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""cfcb757a-c010-4516-89dd-4a88deda7552"",
                    ""path"": ""2DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""72ed9096-3f45-4da6-89b0-2d7bcc0b4b92"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c6a909a9-8842-4d9a-bd10-0d9f8803329d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b92adc29-1947-410b-b096-9e261179c48d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5edaeb1c-dcb2-4ad1-93dd-931b4044b50b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""03b69a49-888d-46e3-8808-8aad13f6e452"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGun"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""502b75c4-9ca3-423b-a72f-1267648b4c7d"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""be3bec07-76cf-428a-934d-544b780c810d"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateGun"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TankControls
        m_TankControls = asset.FindActionMap("TankControls", throwIfNotFound: true);
        m_TankControls_Move = m_TankControls.FindAction("Move", throwIfNotFound: true);
        m_TankControls_RotateGun = m_TankControls.FindAction("RotateGun", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TankControls
    private readonly InputActionMap m_TankControls;
    private List<ITankControlsActions> m_TankControlsActionsCallbackInterfaces = new List<ITankControlsActions>();
    private readonly InputAction m_TankControls_Move;
    private readonly InputAction m_TankControls_RotateGun;
    public struct TankControlsActions
    {
        private @Controls m_Wrapper;
        public TankControlsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_TankControls_Move;
        public InputAction @RotateGun => m_Wrapper.m_TankControls_RotateGun;
        public InputActionMap Get() { return m_Wrapper.m_TankControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TankControlsActions set) { return set.Get(); }
        public void AddCallbacks(ITankControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_TankControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TankControlsActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @RotateGun.started += instance.OnRotateGun;
            @RotateGun.performed += instance.OnRotateGun;
            @RotateGun.canceled += instance.OnRotateGun;
        }

        private void UnregisterCallbacks(ITankControlsActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @RotateGun.started -= instance.OnRotateGun;
            @RotateGun.performed -= instance.OnRotateGun;
            @RotateGun.canceled -= instance.OnRotateGun;
        }

        public void RemoveCallbacks(ITankControlsActions instance)
        {
            if (m_Wrapper.m_TankControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITankControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_TankControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TankControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TankControlsActions @TankControls => new TankControlsActions(this);
    public interface ITankControlsActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnRotateGun(InputAction.CallbackContext context);
    }
}
